remote_theme: pages-themes/leap-day@v0.2.0
theme: jekyll-theme-leap-day
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: VSI Lab Help
description: Help page for VSI Lab
