site_name: VSI Lab
site_description: Training materials on tools and methods for image analysis and deep learning. 
site_url: https://vsilab.github.io/wiki

repo_name: 'UArizona Vision Systems and Intelligence Lab'
repo_url: 'https://github.com/vsi-lab/wiki'
nav:
  - 'Home': index.md
  - 'About': about.md
  - 'Resources':  resources.md
  - 'Instruction': instructions.md
  - 'FAQ': faq.md
  - 'Tools': tools.md


extra_css:
  - css/style.css

theme:
  name: material
  # custom_dir: overrides/
   # setting features for the navigation tab
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - toc.integrate
    - toc.follow
  hide:
    - toc
  
  language: en
  palette:
  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: gold
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
  # Palette toggle for dark mode	
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: orange 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
  
  markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
